### ISSUE TITLE
Always correct Spawn Points

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag-arena-maps#22]
For whatever reason, levels that are ported have randomized spawn points everytime the server is hosted. Now this can be fixed with some code, but with levels that already have spawn points (that literally can't be randomized) still have randomized spawns. And half of the time these spawns are usually broken.

**Comment by EmeraldLoc** [comment]
Oh yea I did the spawn points wrong, I’ll fix this in a bit

**Comment by EmeraldLoc** [comment]
Fixed
